/**
 * Reference-table refresh CLI skeleton (plan U2/U8).
 *
 * Reference sets are append-only versioned snapshots (AGENTS.md rule 8):
 * refreshes INSERT a new version label and never mutate prior versions, so
 * every finding's ref_version_map stays resolvable forever.
 *
 * Seed files are manually downloaded (CMS click-through gates automated
 * fetch) into supabase/seed/raw/<version>/:
 *   - ncci_ptp.csv        code1,code2,modifier_allowed
 *   - mue.csv             code,max_units
 *   - medicare_rates.csv  code,national_rate_cents
 *
 * This script makes NO database connection. It emits idempotent SQL
 * (insert ... on conflict do nothing) to stdout; pipe it into psql or the
 * Supabase SQL editor:
 *
 *   npx tsx scripts/refresh-reference.ts TEST1 > /tmp/ref-TEST1.sql
 *
 * No console.* (AGENTS.md rule 1) — output goes through process.stdout/stderr.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

interface CsvFile {
  header: string[];
  rows: string[][];
}

/** Minimal CSV reader: comma-separated, no quoted fields (our seed formats need none). */
function readCsv(path: string, expectedHeader: string[]): CsvFile {
  const lines = readFileSync(path, "utf8")
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  if (lines.length === 0) {
    fail(`empty CSV: ${path}`);
  }
  const header = lines[0].split(",").map((h) => h.trim());
  if (header.join(",") !== expectedHeader.join(",")) {
    fail(
      `unexpected header in ${path}: got "${header.join(",")}", want "${expectedHeader.join(",")}"`,
    );
  }
  const rows = lines.slice(1).map((line, i) => {
    const cells = line.split(",").map((c) => c.trim());
    if (cells.length !== expectedHeader.length) {
      fail(`row ${i + 2} of ${path} has ${cells.length} cells, want ${expectedHeader.length}`);
    }
    return cells;
  });
  return { header, rows };
}

function fail(message: string): never {
  process.stderr.write(`refresh-reference: ${message}\n`);
  process.exit(1);
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlInt(value: string, context: string): string {
  const n = Number(value);
  if (!Number.isInteger(n) || n < 0) {
    fail(`${context}: "${value}" is not a non-negative integer`);
  }
  return String(n);
}

function sqlNumeric(value: string, context: string): string {
  const n = Number(value);
  if (!Number.isFinite(n) || n < 0) {
    fail(`${context}: "${value}" is not a non-negative number`);
  }
  return String(n);
}

function sqlBool(value: string, context: string): string {
  const v = value.toLowerCase();
  if (v === "true" || v === "1") return "true";
  if (v === "false" || v === "0") return "false";
  return fail(`${context}: "${value}" is not a boolean (true/false/1/0)`);
}

function main(): void {
  const version = process.argv[2];
  if (!version || !/^[A-Za-z0-9_-]+$/.test(version)) {
    fail("usage: refresh-reference.ts <version>   (e.g. 2026Q2, PFS2026, TEST1)");
  }

  const rawDir = join(REPO_ROOT, "supabase", "seed", "raw", version);
  if (!existsSync(rawDir)) {
    fail(`seed directory not found: ${rawDir}`);
  }

  const out: string[] = [
    `-- Generated by scripts/refresh-reference.ts for version ${version}.`,
    `-- Insert-only and idempotent (on conflict do nothing): reference sets are`,
    `-- append-only versioned snapshots; prior versions are never mutated.`,
    `begin;`,
  ];

  const v = sqlString(version);

  // ncci_ptp.csv → public.ref_ncci_ptp
  const ncci = readCsv(join(rawDir, "ncci_ptp.csv"), ["code1", "code2", "modifier_allowed"]);
  for (const [code1, code2, modifierAllowed] of ncci.rows) {
    out.push(
      `insert into public.ref_ncci_ptp (version, code1, code2, modifier_allowed) values ` +
        `(${v}, ${sqlString(code1)}, ${sqlString(code2)}, ${sqlBool(modifierAllowed, `ncci_ptp ${code1}|${code2}`)}) ` +
        `on conflict do nothing;`,
    );
  }

  // mue.csv → public.ref_mue
  const mue = readCsv(join(rawDir, "mue.csv"), ["code", "max_units"]);
  for (const [code, maxUnits] of mue.rows) {
    out.push(
      `insert into public.ref_mue (version, code, max_units) values ` +
        `(${v}, ${sqlString(code)}, ${sqlInt(maxUnits, `mue ${code}`)}) ` +
        `on conflict do nothing;`,
    );
  }

  // medicare_rates.csv → public.ref_medicare_rates (integer cents, always)
  const rates = readCsv(join(rawDir, "medicare_rates.csv"), ["code", "national_rate_cents"]);
  for (const [code, cents] of rates.rows) {
    out.push(
      `insert into public.ref_medicare_rates (version, code, national_rate_cents) values ` +
        `(${v}, ${sqlString(code)}, ${sqlInt(cents, `medicare_rates ${code}`)}) ` +
        `on conflict do nothing;`,
    );
  }

  // fap_policies.csv → public.ref_fap_policies (OPTIONAL — FAP sets refresh
  // on their own cadence; absent file just skips the table). U11.
  const fapPath = join(rawDir, "fap_policies.csv");
  const loadedTables = ["ref_ncci_ptp", "ref_mue", "ref_medicare_rates"];
  if (existsSync(fapPath)) {
    const fap = readCsv(fapPath, [
      "hospital_name",
      "state",
      "threshold_free_fpl",
      "threshold_discount_fpl",
      "source_url",
    ]);
    for (const [name, state, free, discount, url] of fap.rows) {
      const freeSql = free === "" ? "null" : sqlNumeric(free, `fap ${name} free`);
      const discountSql = discount === "" ? "null" : sqlNumeric(discount, `fap ${name} discount`);
      const urlSql = url === "" ? "null" : sqlString(url);
      out.push(
        `insert into public.ref_fap_policies (version, hospital_name, state, threshold_free_fpl, threshold_discount_fpl, source_url) values ` +
          `(${v}, ${sqlString(name)}, ${sqlString(state.toUpperCase())}, ${freeSql}, ${discountSql}, ${urlSql}) ` +
          `on conflict do nothing;`,
      );
    }
    loadedTables.push("ref_fap_policies");
  }

  // Version registry (U11/review F05-F06): the engine resolves "latest" per
  // table from ref_versions by loaded_at — registration IS the activation.
  for (const table of loadedTables) {
    out.push(
      `insert into public.ref_versions (table_name, version) values (${sqlString(table)}, ${v}) ` +
        `on conflict do nothing;`,
    );
  }

  out.push(`commit;`);
  process.stdout.write(out.join("\n") + "\n");
}

main();
